//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_aquila.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Drawing;
    using System.IO;

    public partial class View_DistinctFamilia
    {
        public string Familia { get; set; }
        public int ID { get; set; }
        public string Path { get; set; }
        public string Titulo { get; set; }
        public string Descrição { get; set; }
        public int Desconto { get; set; }
        public double Valor { get; set; }
        [NotMapped]
        public Image Picture
        {
            get
            {
                if (!string.IsNullOrEmpty(Path))
                {
                    if (File.Exists(Path))
                    {
                        return Image.FromFile(Path);
                    }
                }
                return null;
            }
        }
    }
}
